// This file is automatically generated by vscode-react-native@0.2.5
// Please do not modify it manually. All changes will be lost.
try {
    var path = require("path");
    var Launcher = require("/Users/jonathan/.vscode/extensions/vsmobile.vscode-react-native-0.2.5/out/debugger/launcher.js").Launcher;
    new Launcher("/Volumes/MacintoshHD/Projects/Clients/SourceView/SourceViewBible/App", "/Volumes/MacintoshHD/Projects/Clients/SourceView/SourceViewBible/App").launch();
} catch (e) {
    throw new Error("Unable to launch application. Try deleting .vscode/launchReactNative.js and restarting vscode.");
}