/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sourceviewbible_emdros_Emdros */

#ifndef _Included_com_sourceviewbible_emdros_Emdros
#define _Included_com_sourceviewbible_emdros_Emdros
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sourceviewbible_emdros_Emdros
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sourceviewbible_emdros_Emdros_connect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
