require './db/seeds/actants'
require './db/seeds/bso'
require './db/seeds/bso_actants'
require './db/seeds/professions'
require './db/seeds/chronologies'
require './db/seeds/natures'
# require './db/seeds/spheres'
