# require './db/seeds/actants'
# require './db/seeds/sources'
require './db/seeds/sources_actants'
# require './db/seeds/professions'
# require './db/seeds/chronologies'
# require './db/seeds/natures'
# require './db/seeds/spheres'
