/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sourceviewbible_emdros_Emdros */

#ifndef _Included_com_sourceviewbible_emdros_Emdros
#define _Included_com_sourceviewbible_emdros_Emdros
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sourceviewbible_emdros_Emdros
 * Method:    connect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sourceviewbible_emdros_Emdros_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sourceviewbible_emdros_Emdros
 * Method:    string
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sourceviewbible_emdros_Emdros_string
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     com_sourceviewbible_emdros_Emdros
 * Method:    words
 * Signature: ([[JJZ)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_sourceviewbible_emdros_Emdros_words
  (JNIEnv *, jobject, jobjectArray, jlong, jboolean);

/*
 * Class:     com_sourceviewbible_emdros_Emdros
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sourceviewbible_emdros_Emdros_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
